services:
  postgres:
    image: postgres:latest
    container_name: moje_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${PORT}:5432"
    volumes:
      - ./Docker/pgdata:/var/lib/postgresql
